
development:
  adapter: postgresql
  encoding: unicode
  database: mybaby_devel
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['PG_DEV_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: mybaby_devel
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['PG_DEV_PASS'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: blog
  host: 127.10.83.2
  pool: 5
  username: <%= ENV['PG_PROD_USER'] %>
  password: <%= ENV['PG_PROD_PASS'] %>
  port: 5432
