
development:
  adapter: postgresql
  encoding: unicode
  database: dcorckqcc2hf9g
  host: ec2-54-197-241-79.compute-1.amazonaws.com
  pool: 5
  username: pvbxubmjqylpua
  password: A-PS6w-NMz1DchybUm05DwIeWc

test:
  adapter: postgresql
  encoding: unicode
  database: dcorckqcc2hf9g
  host: ec2-54-197-241-79.compute-1.amazonaws.com
  pool: 5
  username: pvbxubmjqylpua
  password: A-PS6w-NMz1DchybUm05DwIeWc

production:
  adapter: postgresql
  encoding: unicode
  database: dcorckqcc2hf9g
  host: ec2-54-197-241-79.compute-1.amazonaws.com
  pool: 5
  username: pvbxubmjqylpua
  password: A-PS6w-NMz1DchybUm05DwIeWc
