
development:
  adapter: postgresql
  encoding: unicode
  database: mybaby_devel
  host: localhost
  pool: 5
  username: postgres
  password: 828526

test:
  adapter: postgresql
  encoding: unicode
  database: mybaby_devel
  host: localhost
  pool: 5
  username: postgres
  password: 828526

production:
  adapter: postgresql
  encoding: unicode
  database: mybaby_pro
  host: localhost
  pool: 5
  username: postgres
  password: 828526
