
development:
  adapter: postgresql
  encoding: unicode
  database: mybaby_devel
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['PG_DEV_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: mybaby_devel
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['PG_DEV_PASS'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['OPENSHIFT_APP_NAME'] %>
  host: <%= ENV['OPENSHIFT_POSTGRESQL_DB_HOST'] %>
  pool: 5
  username: <%= ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD'] %>
  port: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PORT'] %>
