development:
	app_key: "sebzqe9y59a70vf"
	app_secret: "zu9rlay9rjsu3c0"
	access_token: "qeukfgh1in67e84m"
	access_token_secret: "qm7bhv9h8tjzh2u"
	user_id: "51554158"
	access_type: "app_folder"

production:
	app_key: "jy75mizf3v74rjs"
	app_secret: "jn4z0cnxriannnc"
	access_token: "fuv8u5ohu1giz5y2"
	access_token_secret: "sqvkf4eg7xkgbsc"
	user_id: "51554158"
	access_type: "app_folder"