# Here you can specify default options for TinyMCE across all controllers
#
#theme: advanced
default:
  toolbar:
    - insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons
  plugins:
    - table
    - fullscreen
    - image
    - link
    - advlist
    - autolink
    - lists
    - textcolor
    - preview
    - print
    - hr
    - emoticons
    - template
    - paste
    - code
    - charmap
    - anchor
    - pagebreak
    - spellchecker    
    - searchreplace
    - wordcount
    - visualblocks
    - visualchars
    - fullscreen
    - insertdatetime
    - media
    - nonbreaking
    - save
    - contextmenu
    - directionality 

